engine_url: "http://127.0.0.1:8550"
jsonrpc_addr: ":10002"
engine_token_path: "./shared/jwt.hex"
engine_jwt_id: "nexus-validator-1"
data_dir: "./shared/nexus"
chain_config: "./shared/nexus-genesis.json"
execution_genesis_hash: "0xd5e46105991a70a95dfc5416e125b18a41486694b3e4e5f4ba283395ce412f09"
