engine_url: "http://127.0.0.1:28551"
engine_token_path: "multi-validator-shared/v-2/jwt.hex"
engine_jwt_id: "nexus-validator-2"
data_dir: "multi-validator-shared/v-2/nexus"
chain_config: "multi-validator-shared/v-0/nexus-genesis.json"
execution_genesis_hash: "0x520d5f36f145ecbd2e49e4da81575783523ce6f6427027c92a8b1c21662b11ca"
grpc_addr: ":30000"
jsonrpc_addr: ":30002"
network:
  libp2p_addr: 127.0.0.1:30001
seal: true
