engine_url: "http://127.0.0.1:38550"
engine_token_path: "multi-validator-shared/v-3/jwt.hex"
engine_jwt_id: "nexus-validator-3"
data_dir: "multi-validator-shared/v-3/nexus"
chain_config: "multi-validator-shared/v-0/nexus-genesis.json"
execution_genesis_hash: "0xd5e46105991a70a95dfc5416e125b18a41486694b3e4e5f4ba283395ce412f09"
grpc_addr: ":40000"
jsonrpc_addr: ":40002"
network:
  libp2p_addr: 127.0.0.1:40001
seal: true
