engine_url: "http://127.0.0.1:8550"
engine_token_path: "multi-validator-shared/v-3/jwt.hex"
engine_jwt_id: "nexus-validator-3"
data_dir: "multi-validator-shared/v-3/nexus"
chain_config: "multi-validator-shared/v-0/nexus-genesis.json"
execution_genesis_hash: "0x520d5f36f145ecbd2e49e4da81575783523ce6f6427027c92a8b1c21662b11ca"
grpc_addr: ":40000"
jsonrpc_addr: ":40002"
network:
  libp2p_addr: 127.0.0.1:40001
seal: true
