---
name: E2E tests
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_VERBOSE: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Run tests
        run: go test -v -timeout=30m ./e2e/...

      - name: Archive test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-logs
          path: e2e-logs-*/
          retention-days: 30
